language: java
script: ./gradlew dist
install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: E9jf8jd6BEHFpouZ5zDTYAto9VUcxi+3SAxmsMj35fTT9qKUK0pSq/oB351AwMp1KVUUwYRIUO7nTK5A83Zwx77geC1VjC0A2pvAffdLjPltFVG4R534U100e0i4h3UjCGgSSBI3IvLvlvR33+ICIuSgIOx1fD/58I6gKmM5NeAg+Va95mlcD69oLkd1rh5VOWFBhwdfXJSQwSTNgPs1gKxnYHrzMXDAranD6Qu46pZV80UrE/Qjd3C1Z/FczubBJRywHW+oXhvTaRNgUb4WDQxzwezuHuDqyrjnlXkxPvwKQMDzp8Ig51ylUwFBWGEp2Jd5xIpnOyNgJqgFO5UMUcR7gkAu4te3BUGrtTvbbs9n0gT4gMwy5vnbG3b7HdHZvO97rg+rXRgyT9dy3+7xmU3uXvRgkGztfcCU4/++KD56OqwosBDmXZmlzUVx638Nc4nBC4ArmRxOXheUnhipVirsRdyLjiGgoOUMY8rTM9SLsZowqnrHOe+VRMi8jjEg0eqydVE2MoazBgJkYzfT/fW69YfAj4JP40gDqcA0SLP0WLe9r5g5Z6wuaJ2h+TnvqS6sXguAQr92SdLam8wuUQq4qdGExHES8JD2CE+4LqWF840VsdygEppIRGau/uYOoInwFqLjkIAbboa2vOBKREKoglJdbnxCjfuIkkRo5wM=
  file: build/distributions/xmlcalabash1-xslthl-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
