language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: K7T09aIDyGQqMyo8AZiQDJieJUJ8LESvtxJLAqYBMDYeqF7N6w5GPkgF3s9ocXO+DLq4QsqR5TZS43esiEU/mAqi5mPq0UU99zVBQl8WleFZJQy+LrxcF+nQmca6GkrP+ST0Blq3rtIJRrvGcVY46oiI3wCAJslUqoGVKBacrjZ+oY5/QmJL27GaiMXfKG2mQ4vQZmR2S9o/15yQGxIjXgT8ayjTq/OZM0Nats0U4gBaLyZ86pu+IjltmrlcLrednx+B7Z4zR43gss3HyujQVV6LM5MjCS5hppmPhD4ZF8UC69bU8SxVoDTfhq8b5A0FKDY2FrxiO7S3cWnprHtF4LwUHcxU7hsNCCAnRj5tyQDH9r27RE84YAtuSYLRdIqcAbb2eLt6iphX+CWzWicqXP7IExFyaN5FIAS8R8ISRG9PkF++TnVkNcI0NDlKu+EaGdViCPuCWCpaKr3+F8iuTgCsitv29f4qFkMwrlHkkX+R5iBJPKR0erIVCeQt6M5VJ92mgmBUlQzaqa2KflAGu4HIMb33teedQ7mPfaDptIRnSs2imvf9pqgQXqemx2gyCy34uwsPElIIrHmLLgbXoTzMINp2OtemQBjPZ+XhLAuak80p2AAkmWZAKSc7CoZr8KqhMsRvVZivlLSzklo+3F98MfnELxYfm2byVmzBFF0=
  skip_cleanup: true
  file: build/distributions/xmlcalabash1-xslthl-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
